server:
  port: 6011
mybatis: #mybatis
  type-aliases-package: com.inta.common.atom
spring:
  application:
    name: cloud-atom
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://123hk:123456@localhost:6010/eureka
    healthcheck:
      enabled: true                             # 开启健康检查（依赖spring-boot-starter-actuator）
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
