server:
  port: 9201

spring:
  application:
    name: cloud-service
#user:
#  url: http://localhost:9001/user/
eureka:
  client:
    serviceUrl:
#      defaultZone: http://admin:123@localhost:4396/eureka
      defaultZone: http://admin:123@peer1:11001/eureka,http://admin:123@peer2:11002/eureka

feign:
  hystrix:
    enabled: true # feign 默认关闭 hystrix,需要熔断时必须加上该配置